### ISSUE TITLE
Qn: How to pass params

### ISSUE THREAD

**Issue by bsr203** [Baransu/bs-react-navigation#5]
Hi.
Thanks to your recent changes, I could run examples from  `BottomTabNavigator` branch. I wonder is it possible to pass different record/object as params to screens. say we define  ` First` as 

```
type firstProps = {
.
name: string
};

let component = ReasonReact.statelessComponent("First");
let make = (~navigation, ~firstProps, _) => {
...
```

then, how can we pass the props
```
onPress={
          _ =>
            Navigation.navigate(
              navigation,
              ~routeName="First",
              ~params={"name": "s"},
              (),
            )
        }
```
```
  This has type:
    BsReactNavigation.Route.t(screenProps, {. name: string},
                               BsReactNavigation.StackNavigationOptions.t)
      (defined as
      BsReactNavigation.Route.t(screenProps, {. name: string},
                                 BsReactNavigation.StackNavigationOptions.t))
  But somewhere wanted:
    BsReactNavigation.StackNavigator.route(screenProps, params) (defined as
      BsReactNavigation.Route.t(screenProps, params,
                                 BsReactNavigation.StackNavigationOptions.t))

  The incompatible parts:
    {. name: string}
    vs
    params
```
I see methods to get params on `navigation.state` and may be a better way.
I am bit new to reason, and will spend some more time to understand the code. 

thank you.
bsr

**Comment by Baransu** [comment]
Thank you for the issue 🙂 I'll add example how to pass params from one screen to another.

**Comment by Baransu** [comment]
I've added example how to pass params between two screens. Also https://github.com/Baransu/bs-react-navigation/pull/3 with basic support for `BottomTabNavigator` landed so feel free to try it 🙂

**Comment by bsr203** [comment]
Thanks for the example. I am yet to try it, but left a comment [here](https://github.com/baransu/bs-react-navigation/commit/7f32a6d91e9eaa4f9b585b8d9ebf917f72d43447#r30511175) Thanks again for your work on this.
